replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

contentStorage:
  enabled: true
  size: 5Gi
  accessModes:
    - ReadWriteMany
  storageClass: ""
  annotations: {}

pgvector:
  enabled: true
  # host defaults to <release-name>-pgvector automatically — override only if needed
  host: ""
  port: 5432
  batchSize: 100
  auth:
    username: "postgres"
    database: "postgres"
  initdb:
    scripts:
      init_pgvector.sql: |
        CREATE EXTENSION IF NOT EXISTS vector;
  config:
  postgresqlMaxConnections: 200
  postgresqlSharedBuffers: "256MB"
  postgresqlEffectiveCacheSize: "1GB"
  postgresqlWorkMem: "256MB"
  postgresqlMaintenanceWorkMem: "4GB"
  customUser:
    existingSecret: "ekh-local-credentials"
    secretKeys:
      name: "ekhuser"
      password:
        fromSecretKey: "postgres-password"
      database: "postgres"