apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ekh.fullname" . }}
  labels: 
    {{ include "ekh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 1 }}
  selector:
    matchLabels:
      {{ include "ekh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
      labels:
        {{- include "ekh.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          env:
            - name: PYTORCH_ALLOC_CONF
              value: {{ .Values.pytorch.allocConf | quote }}
            - name: PYTORCH_CUDA_GPU_CAP
              value: {{ .Values.pytorch.cudaGpuCap | quote }}
            - name: LLAMA_CUDA
              value: {{ .Values.pytorch.llamaCuda | quote }}
            {{- with .Values.wikiEmbeddingModel }}
            - name: WIKIPEDIA_EMBEDDING_MODEL_BACKEND
              value: {{ .backend | quote }}
            - name: WIKIPEDIA_EMBEDDING_MODEL_CLEANUP
              value: {{ .cleanup | quote }}
            - name: WIKIPEDIA_EMBEDDING_MODEL_BATCH_SIZE
              value: {{ .batchSize | quote }}
            - name: WIKIPEDIA_EMBEDDING_MODEL_MAX_LENGTH
              value: {{ .maxLength | quote }}
            - name: WIKIPEDIA_EMBEDDING_MODEL_MAX_DIM
              value: {{ .maxDim | quote }}
            - name: WIKIPEDIA_EMBEDDING_MODEL_DTYPE
              value: {{ .dtype | quote }}
            {{- end }}
            {{- $pgvectorSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-pgvector" .Release.Name) }}
            {{- if $pgvectorSecret }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $pgvectorSecret.metadata.name }}
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ $pgvectorSecret.metadata.name }}
                  key: database
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $pgvectorSecret.metadata.name }}
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ $pgvectorSecret.metadata.name }}
                  key: port
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $pgvectorSecret.metadata.name }}
                  key: postgres-password
            {{- else }}
            {{- with .Values.pgvector }}
            - name: POSTGRES_USER
              value: {{ .customUser.username | default .auth.username | quote }}
            - name: POSTGRES_DB
              value: {{ .customUser.database | default .auth.database | quote }}
            - name: POSTGRES_HOST
              value: {{ .host | default (printf "%s-pgvector" $.Release.Name) | quote }}
            - name: POSTGRES_PORT
              value: {{ .port | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .password | quote }}
            {{- end }}
            {{- end }}
            {{- $rabbitmqSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-rabbitmq" .Release.Name) }}
            {{- $rabbitmqPassword := .Values.rabbitmq.auth.password }}
            {{- if $rabbitmqSecret }}
            {{- $rabbitmqPassword = index $rabbitmqSecret.data "password" | b64dec }}
            {{- end }}
            - name: RABBITMQ_URL
              value: {{ printf "amqp://%s:%s@%s-rabbitmq:%v/" .Values.rabbitmq.auth.username $rabbitmqPassword .Release.Name .Values.rabbitmq.port | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.contentStorage.enabled }}
          volumeMounts:
            - name: content
              mountPath: /app/content
          {{- end }}
      {{- if .Values.contentStorage.enabled }}
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: {{ include "ekh.fullname" . }}-content
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
