{{- $secretName := printf "%s-credentials" (include "ekh.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "ekh.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret $existingSecret.data }}
  {{- $rabbitPassword := index $existingSecret.data "rabbitmq-password" | b64dec }}
  postgres-password: {{ index $existingSecret.data "postgres-password" }}
  rabbitmq-password: {{ index $existingSecret.data "rabbitmq-password" }}
  rabbitmq-erlang-cookie-key: {{ index $existingSecret.data "rabbitmq-erlang-cookie-key" }}
  rabbitmq-url: {{ printf "amqp://%s:%s@%s-rabbitmq:%d/%s" .Values.rabbitmq.auth.username $rabbitPassword (printf "%s-rabbitmq" $.Release.Name) (.Values.rabbitmq.port | int) .Values.rabbitmq.vhost | b64enc | quote }}
  {{- else }}
  {{- $rabbitPassword := randAlphaNum 32 }}
  postgres-password: {{ randAlphaNum 32 | b64enc | quote }}
  rabbitmq-password: {{ $rabbitPassword | b64enc | quote }}
  rabbitmq-erlang-cookie-key: {{ randAlphaNum 32 | b64enc | quote }}
  rabbitmq-url: {{ printf "amqp://%s:%s@%s-rabbitmq:%d/%s" .Values.rabbitmq.auth.username $rabbitPassword (printf "%s-rabbitmq" $.Release.Name) (.Values.rabbitmq.port | int) .Values.rabbitmq.vhost | b64enc | quote }}
  {{- end }}
