{{- $secretName := printf "%s-credentials" (include "ekh.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "ekh.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $rabbitPassword := randAlphaNum 32 }}
  postgres-password: {{ randAlphaNum 32 | quote }}
  rabbitmq-password: {{ $rabbitPassword | b64enc | quote }}
  rabbitmq-erlang-cookie-key: {{ randAlphaNum 32 | b64enc | quote }}
  rabbitmq-url: {{ printf "amqp://%s:%s@%s-rabbitmq:%d/" .Values.rabbitmq.auth.username $rabbitPassword ($.Release.Name) (.Values.rabbitmq.port | int) | quote }}
